/**
 * Video player constants
 */

export const VIDEO_CONSTANTS = {
  // Timeouts
  CONTROLS_HIDE_TIMEOUT: 3000,

  // Dimensions
  PLAY_BUTTON_SIZE: 80,
  PLAY_BUTTON_RADIUS: 40,
  PLAY_ICON_SIZE: 48,
  BACK_ICON_SIZE: 24,
  STATE_ICON_SIZE: 64,

  // Spacing
  OVERLAY_PADDING_TOP: 20,
  OVERLAY_PADDING_BOTTOM: 40,
  OVERLAY_PADDING_HORIZONTAL: 20,
  BACK_BUTTON_PADDING_VERTICAL: 8,
  BACK_BUTTON_PADDING_HORIZONTAL: 12,
  BACK_BUTTON_BORDER_RADIUS: 8,
  RETRY_BUTTON_PADDING_HORIZONTAL: 24,
  RETRY_BUTTON_PADDING_VERTICAL: 12,
  STATE_CONTAINER_PADDING: 32,

  // Typography
  BACK_TEXT_SIZE: 16,
  CHANNEL_NAME_SIZE: 18,
  LOADING_TITLE_SIZE: 20,
  ERROR_TITLE_SIZE: 20,
  SUBTITLE_SIZE: 14,
  RETRY_BUTTON_TEXT_SIZE: 16,

  // Margins
  BACK_TEXT_MARGIN_LEFT: 8,
  STATE_TITLE_MARGIN_TOP: 16,
  STATE_TITLE_MARGIN_BOTTOM: 8,
  ERROR_RETRY_MARGIN_BOTTOM: 24,

  // Opacity values
  OVERLAY_BACKGROUND_OPACITY: 0.3,
  BUTTON_BACKGROUND_OPACITY: 0.6,
  STATE_BACKGROUND_OPACITY: 0.8,
  RETRY_BUTTON_OPACITY: 0.2,

  // Line height
  SUBTITLE_LINE_HEIGHT: 20,
} as const;