/**
 * Video player constants
 */

export const VIDEO_CONSTANTS = {
  // Timeouts
  CONTROLS_HIDE_TIMEOUT: 3000,

  // Dimensions
  PLAY_BUTTON_SIZE: 80,
  PLAY_BUTTON_RADIUS: 40,
  PLAY_ICON_SIZE: 48,
  BACK_ICON_SIZE: 24,
  STATE_ICON_SIZE: 64,

  // Spacing
  OVERLAY_PADDING_TOP: 20,
  OVERLAY_PADDING_BOTTOM: 40,
  OVERLAY_PADDING_HORIZONTAL: 20,
  BACK_BUTTON_PADDING_VERTICAL: 8,
  BACK_BUTTON_PADDING_HORIZONTAL: 12,
  BACK_BUTTON_BORDER_RADIUS: 8,
  RETRY_BUTTON_PADDING_HORIZONTAL: 24,
  RETRY_BUTTON_PADDING_VERTICAL: 12,
  STATE_CONTAINER_PADDING: 32,

  // Typography
  BACK_TEXT_SIZE: 16,
  CHANNEL_NAME_SIZE: 18,
  LOADING_TITLE_SIZE: 20,
  ERROR_TITLE_SIZE: 20,
  SUBTITLE_SIZE: 14,
  RETRY_BUTTON_TEXT_SIZE: 16,

  // Margins
  BACK_TEXT_MARGIN_LEFT: 8,
  STATE_TITLE_MARGIN_TOP: 16,
  STATE_TITLE_MARGIN_BOTTOM: 8,
  ERROR_RETRY_MARGIN_BOTTOM: 24,

  // Opacity values
  OVERLAY_BACKGROUND_OPACITY: 0.3,
  BUTTON_BACKGROUND_OPACITY: 0.6,
  STATE_BACKGROUND_OPACITY: 0.8,
  RETRY_BUTTON_OPACITY: 0.2,

  // Line height
  SUBTITLE_LINE_HEIGHT: 20,

  // Seek bar
  SEEK_BAR_HEIGHT: 4,
  SEEK_BAR_THUMB_SIZE: 16,
  SEEK_BAR_ACTIVE_THUMB_SIZE: 24,
  SEEK_BAR_PADDING_HORIZONTAL: 16,
  TIME_LABEL_SIZE: 12,
  // Gesture zones
  GESTURE_BOTTOM_ZONE_RATIO: 0.45,
  GESTURE_SIDE_ZONE_RATIO: 0.30,
  GESTURE_MIN_DISTANCE: 10,

  // Gesture sensitivity
  GESTURE_SEEK_SECONDS_PER_PX: 0.75,
  GESTURE_SLIDER_SENSITIVITY: 1.25,

  // Gesture indicator dimensions & timing
  GESTURE_INDICATOR_FADE_MS: 200,
  GESTURE_INDICATOR_LINGER_MS: 500,
  GESTURE_SLIDER_WIDTH: 48,
  GESTURE_SLIDER_HEIGHT_RATIO: 0.75,
  GESTURE_SLIDER_TRACK_OVERHEAD: 58, // py-4 (32) + icon (18) + gap (8)
  GESTURE_MIN_DIRECTION_THRESHOLD: 3,
} as const;